version: "3.9"
services:
  client:
    build:
      context: ./client
      target: dev
    ports:
      - "3030:3030"
    volumes:
      - ./client:/client
      - client-node-modules:/client/node_modules


volumes:
  client-node-modules: